//! Python parity harness for bot-math kernel modules.
//!
//! Loads `strategy/rust_fixtures/*.json` fixtures (generated by the
//! Python reference) and asserts byte-exact Rust output at the tolerance
//! stated in each fixture case.
//!
//! Each `parity_<module>` test iterates every case in the file and compares
//! Rust output to the Python `expected` within `tolerance`. Failures are
//! aggregated with per-case name/input/expected/actual/diff logging so a
//! single test invocation surfaces every mismatch.
//!
//! Env override: `DOL_MATH_PARITY_DIR` → absolute path to `rust_fixtures/`.

use serde::Deserialize;
use std::path::PathBuf;

use bot_math::{
    breakeven::{break_even_hold_at_mean, break_even_hold_fixed_point},
    cost::slippage,
    leverage::{bernstein_leverage_bound, critical_aum},
    ou::ou_time_averaged_spread,
    phi::{phi, phi_derivative},
    routing::{cap_routing, mandate_floor},
};
use bot_types::{AnnualizedRate, AumFraction, Dimensionless, HourlyRate, Hours, Mandate, Usd};

fn fixtures_dir() -> PathBuf {
    if let Ok(p) = std::env::var("DOL_MATH_PARITY_DIR") {
        return PathBuf::from(p);
    }
    // CARGO_MANIFEST_DIR → crates/bot-tests; ../ → crates; ../../ → bot-rs;
    // ../../../ → dol-public (monorepo root). Then strategy/rust_fixtures.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("strategy")
        .join("rust_fixtures")
}

#[derive(Debug, Deserialize)]
struct Case<I, E> {
    name: String,
    input: I,
    expected: E,
    tolerance: f64,
    #[allow(dead_code)]
    #[serde(default)]
    notes: Option<String>,
}

fn load_cases<I, E>(filename: &str) -> Vec<Case<I, E>>
where
    I: for<'de> Deserialize<'de>,
    E: for<'de> Deserialize<'de>,
{
    let path = fixtures_dir().join(filename);
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("could not read fixture {}: {}", path.display(), e));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("could not parse fixture {}: {}", path.display(), e))
}

fn approx_eq(actual: f64, expected: f64, tol: f64) -> bool {
    if actual.is_nan() && expected.is_nan() {
        return true;
    }
    if !actual.is_finite() || !expected.is_finite() {
        return actual == expected;
    }
    (actual - expected).abs() <= tol.max(f64::EPSILON)
}

macro_rules! parity_scalar {
    ($test_name:ident, $file:expr, $input:ty, $call:expr) => {
        #[test]
        fn $test_name() {
            #[derive(Deserialize)]
            struct Expected {
                result: f64,
            }
            let cases: Vec<Case<$input, Expected>> = load_cases($file);
            assert!(!cases.is_empty(), "fixture {} has no cases", $file);
            let mut failures = Vec::new();
            for case in &cases {
                let actual = ($call)(&case.input);
                if !approx_eq(actual, case.expected.result, case.tolerance) {
                    failures.push(format!(
                        "[{}] actual={} expected={} tol={} diff={:.3e}",
                        case.name,
                        actual,
                        case.expected.result,
                        case.tolerance,
                        (actual - case.expected.result).abs()
                    ));
                }
            }
            assert!(
                failures.is_empty(),
                "{}/{} parity failures for {}:\n{}",
                failures.len(),
                cases.len(),
                $file,
                failures.join("\n")
            );
            println!("parity: {} OK ({} cases)", $file, cases.len());
        }
    };
}

// ── phi ──────────────────────────────────────────────────────────────────────
//
// phi.json mixes two case shapes: scalar `{input:{x:f64}, expected:{result:f64}}`
// and vector `{input:{xs:[f64]}, expected:{values:[f64]}}`. We test both.

#[test]
fn parity_phi() {
    let path = fixtures_dir().join("phi.json");
    let contents = std::fs::read_to_string(&path).expect("read phi.json");
    let cases: Vec<serde_json::Value> = serde_json::from_str(&contents).expect("parse phi.json");
    assert!(!cases.is_empty(), "no phi cases");
    let mut failures = Vec::new();
    let mut scalar_count = 0usize;
    let mut vector_count = 0usize;
    for case in &cases {
        let name = case["name"].as_str().unwrap_or("?").to_string();
        let tol = case["tolerance"].as_f64().unwrap_or(1e-12);
        let input = &case["input"];
        let expected = &case["expected"];
        // Dispatch phi(x) vs phi'(x) by case name prefix.
        let is_derivative = name.starts_with("phi_derivative_");
        if let Some(x) = input.get("x").and_then(|v| v.as_f64()) {
            scalar_count += 1;
            let got = if is_derivative {
                phi_derivative(x)
            } else {
                phi(x)
            };
            let exp = expected["result"].as_f64().unwrap_or(f64::NAN);
            if !approx_eq(got, exp, tol) {
                failures.push(format!(
                    "[{name}] ({}) x={x} got={got} exp={exp}",
                    if is_derivative { "φ'" } else { "φ" }
                ));
            }
        } else if let Some(xs_arr) = input.get("xs").and_then(|v| v.as_array()) {
            vector_count += 1;
            let xs: Vec<f64> = xs_arr.iter().filter_map(|v| v.as_f64()).collect();
            let empty_vec: Vec<serde_json::Value> = Vec::new();
            let expected_vals: Vec<f64> = expected["values"]
                .as_array()
                .unwrap_or(&empty_vec)
                .iter()
                .filter_map(|v| v.as_f64())
                .collect();
            if xs.len() != expected_vals.len() {
                failures.push(format!("[{name}] xs/values length mismatch"));
                continue;
            }
            for (x, exp) in xs.iter().zip(expected_vals.iter()) {
                let got = phi(*x);
                if !approx_eq(got, *exp, tol) {
                    failures.push(format!("[{name}] x={} got={} exp={}", x, got, exp));
                }
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} phi failures ({} scalar, {} vector cases):\n{}",
        failures.len(),
        scalar_count,
        vector_count,
        failures.join("\n")
    );
    println!(
        "parity: phi.json OK ({} scalar + {} vector cases)",
        scalar_count, vector_count
    );
}

// ── slippage ─────────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct SlippageInput {
    notional_usd: f64,
    oi_usd: f64,
    vol_24h_usd: f64,
}
parity_scalar!(
    parity_slippage,
    "slippage.json",
    SlippageInput,
    |i: &SlippageInput| slippage(Usd(i.notional_usd), Usd(i.oi_usd), Usd(i.vol_24h_usd)).0
);

// ── ou_time_averaged_spread ──────────────────────────────────────────────────

#[derive(Deserialize)]
struct OuInput {
    d0: f64,
    mu: f64,
    theta_ou: f64,
    tau_h: f64,
}
parity_scalar!(
    parity_ou,
    "ou_time_averaged_spread.json",
    OuInput,
    |i: &OuInput| ou_time_averaged_spread(
        AnnualizedRate(i.d0),
        AnnualizedRate(i.mu),
        HourlyRate(i.theta_ou),
        Hours(i.tau_h),
    )
    .0
);

// ── break_even_hold (mixed at-mean + fixed-point cases) ─────────────────────
//
// Cases named `be_at_mean_*` use `break_even_hold_at_mean` (closed form).
// Cases named `be_fixed_point_*` require the fixed-point iteration because
// they supply `d0` and `theta_ou`.

#[test]
fn parity_break_even_hold() {
    let path = fixtures_dir().join("break_even_hold.json");
    let contents = std::fs::read_to_string(&path).expect("read break_even_hold.json");
    let cases: Vec<serde_json::Value> =
        serde_json::from_str(&contents).expect("parse break_even_hold.json");
    assert!(!cases.is_empty(), "no cases");
    let mut failures = Vec::new();
    for case in &cases {
        let name = case["name"].as_str().unwrap_or("?").to_string();
        let tol = case["tolerance"].as_f64().unwrap_or(1e-9);
        let input = &case["input"];
        let exp = case["expected"]["result"].as_f64().unwrap_or(f64::NAN);
        let mu = input["mu"].as_f64().expect("mu");
        let c = input["c_round_trip"].as_f64().expect("c_round_trip");
        let rho = input["rho_comp"].as_f64().unwrap_or(0.0);
        let got = if name.starts_with("be_fixed_point_") {
            let d0 = input["d0"].as_f64().expect("d0");
            let theta = input["theta_ou"].as_f64().expect("theta_ou");
            let initial =
                break_even_hold_at_mean(AnnualizedRate(mu), Dimensionless(c), Dimensionless(rho))
                    .map(|h| h.0)
                    .unwrap_or(100.0);
            break_even_hold_fixed_point(
                AnnualizedRate(d0),
                AnnualizedRate(mu),
                HourlyRate(theta),
                Dimensionless(c),
                Dimensionless(rho),
                Hours(initial),
                500,
                1e-9,
            )
            .map(|h| h.0)
            .unwrap_or(f64::NAN)
        } else {
            break_even_hold_at_mean(AnnualizedRate(mu), Dimensionless(c), Dimensionless(rho))
                .map(|h| h.0)
                .unwrap_or(f64::NAN)
        };
        if !approx_eq(got, exp, tol) {
            failures.push(format!(
                "[{name}] got={got} exp={exp} tol={tol} diff={:.3e}",
                (got - exp).abs()
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{}/{} break_even failures:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
    println!("parity: break_even_hold.json OK ({} cases)", cases.len());
}

// ── bernstein_leverage_bound ─────────────────────────────────────────────────

#[derive(Deserialize)]
struct BernsteinInput {
    mmr: f64,
    delta_per_h: f64,
    sigma_per_h: f64,
    tau_h: f64,
    epsilon: f64,
}
parity_scalar!(
    parity_bernstein_leverage,
    "bernstein_leverage.json",
    BernsteinInput,
    |i: &BernsteinInput| bernstein_leverage_bound(
        Dimensionless(i.mmr),
        Dimensionless(i.delta_per_h),
        Dimensionless(i.sigma_per_h),
        Hours(i.tau_h),
        i.epsilon,
    )
    .map(|l| l as f64)
    .unwrap_or(f64::NAN)
);

// ── critical_aum ─────────────────────────────────────────────────────────────

// critical_aum fixture uses JSON "inf" strings for infinite results.
// We use a raw serde_json pass to handle both numeric and "inf" expected values.
#[test]
fn parity_critical_aum() {
    let path = fixtures_dir().join("critical_aum.json");
    let contents = std::fs::read_to_string(&path).expect("read critical_aum.json");
    let cases: Vec<serde_json::Value> =
        serde_json::from_str(&contents).expect("parse critical_aum.json");
    assert!(!cases.is_empty());
    let mut failures = Vec::new();
    for case in &cases {
        let name = case["name"].as_str().unwrap_or("?").to_string();
        let tol = case["tolerance"].as_f64().unwrap_or(1e-6);
        let input = &case["input"];
        let pi_pac = input["pi_pac"].as_f64().expect("pi_pac");
        let tau_be = input["tau_be_h"].as_f64().expect("tau_be_h");
        let tau = input["tau_h"].as_f64().expect("tau_h");
        let theta = input["theta_impact"].as_f64().expect("theta_impact");
        let lev = input["leverage"].as_u64().expect("leverage") as u32;
        let m_pos = input["m_pos"].as_f64().expect("m_pos");
        let got = critical_aum(
            Usd(pi_pac),
            Hours(tau_be),
            Hours(tau),
            Dimensionless(theta),
            lev,
            AumFraction(m_pos),
        )
        .0;
        // Expected may be a number or the string "inf"/"Infinity".
        let exp_v = &case["expected"]["result"];
        let exp = if let Some(x) = exp_v.as_f64() {
            x
        } else if let Some(s) = exp_v.as_str() {
            match s.to_ascii_lowercase().as_str() {
                "inf" | "+inf" | "infinity" => f64::INFINITY,
                "-inf" | "-infinity" => f64::NEG_INFINITY,
                "nan" => f64::NAN,
                other => {
                    failures.push(format!("[{name}] unknown expected string: {other}"));
                    continue;
                }
            }
        } else {
            failures.push(format!("[{name}] expected is neither number nor string"));
            continue;
        };
        if !approx_eq(got, exp, tol) {
            failures.push(format!(
                "[{name}] got={got} exp={exp} tol={tol} diff={:.3e}",
                (got - exp).abs()
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{}/{} critical_aum failures:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
    println!("parity: critical_aum.json OK ({} cases)", cases.len());
}

// ── mandate_floor ────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct MandateFloorInput {
    cust_min: f64,
    buf_min: f64,
    cut_customer: f64,
    cut_buffer: f64,
}

parity_scalar!(
    parity_mandate_floor,
    "mandate_floor.json",
    MandateFloorInput,
    |i: &MandateFloorInput| {
        let m = Mandate {
            customer_apy_min: AnnualizedRate(i.cust_min),
            buffer_apy_min: AnnualizedRate(i.buf_min),
            cut_customer: Dimensionless(i.cut_customer),
            cut_buffer: Dimensionless(i.cut_buffer),
            ..Mandate::default()
        };
        mandate_floor(&m).0
    }
);

// ── cap_routing ──────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct CapRoutingInput {
    vault_gross: f64,
    #[serde(default, rename = "cust_max")]
    customer_apy_max: Option<f64>,
    #[serde(default, rename = "buf_max")]
    buffer_apy_max: Option<f64>,
    #[serde(default)]
    cut_customer: Option<f64>,
    #[serde(default)]
    cut_buffer: Option<f64>,
    #[serde(default)]
    cut_reserve: Option<f64>,
}

#[derive(Deserialize)]
struct CapRoutingExpected {
    customer: f64,
    buffer: f64,
    reserve: f64,
}

#[test]
fn parity_cap_routing() {
    let cases: Vec<Case<CapRoutingInput, CapRoutingExpected>> = load_cases("cap_routing.json");
    assert!(!cases.is_empty(), "no cap_routing cases");
    let mut failures = Vec::new();
    for case in &cases {
        let base = Mandate::default();
        let m = Mandate {
            customer_apy_max: AnnualizedRate(
                case.input
                    .customer_apy_max
                    .unwrap_or(base.customer_apy_max.0),
            ),
            buffer_apy_max: AnnualizedRate(
                case.input.buffer_apy_max.unwrap_or(base.buffer_apy_max.0),
            ),
            cut_customer: Dimensionless(case.input.cut_customer.unwrap_or(base.cut_customer.0)),
            cut_buffer: Dimensionless(case.input.cut_buffer.unwrap_or(base.cut_buffer.0)),
            cut_reserve: Dimensionless(case.input.cut_reserve.unwrap_or(base.cut_reserve.0)),
            ..base
        };
        let alloc = cap_routing(AnnualizedRate(case.input.vault_gross), &m);
        let tol = case.tolerance;
        if !approx_eq(alloc.customer.0, case.expected.customer, tol)
            || !approx_eq(alloc.buffer.0, case.expected.buffer, tol)
            || !approx_eq(alloc.reserve.0, case.expected.reserve, tol)
        {
            failures.push(format!(
                "[{}] actual=({}, {}, {}) expected=({}, {}, {})",
                case.name,
                alloc.customer.0,
                alloc.buffer.0,
                alloc.reserve.0,
                case.expected.customer,
                case.expected.buffer,
                case.expected.reserve,
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{}/{} cap_routing failures:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
    println!("parity: cap_routing.json OK ({} cases)", cases.len());
}
