//! Python parity harness for `bot_strategy_v3::funding_cycle_lock`.
//!
//! Loads the fixture file at
//! `strategy/output/rust_parity/funding_cycle_lock_fixtures.json`
//! (generated by `strategy/scripts/generate_funding_lock_parity_fixtures.py`)
//! and asserts that every Rust call matches the Python reference output to
//! exact integer equality and `1e-9` float tolerance.
//!
//! Fixture schema (per case):
//! ```json
//! {
//!   "id": "enforce_locked_rejects_flip",
//!   "function": "enforce",
//!   "input": { ... function-specific ... },
//!   "expected": { ... function-specific ... },
//!   "note": "optional free-text"
//! }
//! ```
//!
//! The path to the fixture file is resolved via the
//! `DOL_FUNDING_LOCK_PARITY_FIXTURE` env var (if set), or walks up from
//! `CARGO_MANIFEST_DIR` to the sibling `strategy/output/rust_parity/` tree.
//! If no fixture is present the test skips cleanly (no false failure).

use bot_strategy_v3::funding_cycle_lock::{
    cycle_index, cycle_phase, enforce, is_locked, open_cycle, seconds_to_cycle_end,
    would_violate_lock, CycleState,
};
use serde::Deserialize;
use serde_json::Value;
use std::path::PathBuf;

// ─────────────────────────────────────────────────────────────────────────────
// Fixture shapes
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct ParityDoc {
    cases: Vec<ParityCase>,
}

#[derive(Debug, Deserialize)]
struct ParityCase {
    id: String,
    function: String,
    input: Value,
    expected: Value,
    #[serde(default)]
    #[allow(dead_code)]
    note: String,
}

/// Float tolerance for per-case float-field comparisons.
const FLOAT_TOL: f64 = 1e-9;

// ─────────────────────────────────────────────────────────────────────────────
// Fixture loader
// ─────────────────────────────────────────────────────────────────────────────

fn fixture_path() -> PathBuf {
    if let Ok(p) = std::env::var("DOL_FUNDING_LOCK_PARITY_FIXTURE") {
        if !p.is_empty() {
            return PathBuf::from(p);
        }
    }

    // CARGO_MANIFEST_DIR → crates/bot-tests
    // ../.. → crates
    // ../../.. → bot-rs
    // ../../../.. → monorepo root
    // then strategy/output/rust_parity/funding_cycle_lock_fixtures.json
    let manifest = std::env::var("CARGO_MANIFEST_DIR")
        .unwrap_or_else(|_| panic!("CARGO_MANIFEST_DIR is not set; run via `cargo test`."));
    PathBuf::from(manifest)
        .join("..")
        .join("..")
        .join("..")
        .join("..")
        .join("strategy")
        .join("output")
        .join("rust_parity")
        .join("funding_cycle_lock_fixtures.json")
}

fn load_fixture_doc() -> Option<ParityDoc> {
    let path = fixture_path();
    let raw = match std::fs::read_to_string(&path) {
        Ok(s) => s,
        Err(_) => return None,
    };
    Some(serde_json::from_str(&raw).unwrap_or_else(|e| {
        panic!(
            "Could not parse funding_cycle_lock parity fixture at {:?}: {}",
            path, e
        )
    }))
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers for reading the JSON Value shapes
// ─────────────────────────────────────────────────────────────────────────────

fn get_f64(v: &Value, key: &str) -> f64 {
    v.get(key)
        .and_then(|x| x.as_f64())
        .unwrap_or_else(|| panic!("expected '{}' as f64 in {:?}", key, v))
}

fn get_i64(v: &Value, key: &str) -> i64 {
    v.get(key)
        .and_then(|x| x.as_i64())
        .unwrap_or_else(|| panic!("expected '{}' as i64 in {:?}", key, v))
}

fn get_i8(v: &Value, key: &str) -> i8 {
    let n = get_i64(v, key);
    assert!(
        (-128..=127).contains(&n),
        "'{}' out of i8 range: {}",
        key,
        n
    );
    n as i8
}

fn get_bool(v: &Value, key: &str) -> bool {
    v.get(key)
        .and_then(|x| x.as_bool())
        .unwrap_or_else(|| panic!("expected '{}' as bool in {:?}", key, v))
}

/// Parse an optional `state` object from the fixture input. Returns `None`
/// if the field is `null` or missing.
fn parse_optional_state(v: &Value) -> Option<CycleState> {
    match v {
        Value::Null => None,
        Value::Object(_) => Some(CycleState {
            cycle_index: get_i64(v, "cycle_index"),
            h_c: get_i8(v, "h_c"),
            n_c: get_f64(v, "N_c"),
            opened_at: get_f64(v, "opened_at"),
            cycle_seconds: get_i64(v, "cycle_seconds"),
        }),
        _ => panic!("expected state to be null or object, got {:?}", v),
    }
}

fn assert_close(actual: f64, expected: f64, case_id: &str, field: &str) {
    let diff = (actual - expected).abs();
    assert!(
        diff < FLOAT_TOL,
        "case '{}' field '{}' mismatch: actual={} expected={} diff={} (tol={})",
        case_id,
        field,
        actual,
        expected,
        diff,
        FLOAT_TOL
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// Per-function dispatch
// ─────────────────────────────────────────────────────────────────────────────

fn check_cycle_index(c: &ParityCase) {
    let t = get_f64(&c.input, "t");
    let cs = get_i64(&c.input, "cycle_seconds");
    let actual = cycle_index(t, cs);
    let expected = get_i64(&c.expected, "value");
    assert_eq!(
        actual, expected,
        "case '{}' cycle_index mismatch: got {}, expected {}",
        c.id, actual, expected
    );
}

fn check_cycle_phase(c: &ParityCase) {
    let t = get_f64(&c.input, "t");
    let cs = get_i64(&c.input, "cycle_seconds");
    let actual = cycle_phase(t, cs);
    let expected = get_f64(&c.expected, "value");
    assert_close(actual, expected, &c.id, "value");
}

fn check_seconds_to_cycle_end(c: &ParityCase) {
    let t = get_f64(&c.input, "t");
    let cs = get_i64(&c.input, "cycle_seconds");
    let actual = seconds_to_cycle_end(t, cs);
    let expected = get_f64(&c.expected, "value");
    assert_close(actual, expected, &c.id, "value");
}

fn check_is_locked(c: &ParityCase) {
    let state = parse_optional_state(&c.input["state"]);
    let now = get_f64(&c.input, "now");
    let actual = is_locked(state.as_ref(), now);
    let expected = get_bool(&c.expected, "value");
    assert_eq!(
        actual, expected,
        "case '{}' is_locked mismatch: got {}, expected {}",
        c.id, actual, expected
    );
}

fn check_open_cycle(c: &ParityCase) {
    let now = get_f64(&c.input, "now");
    let h_c = get_i8(&c.input, "h_c");
    let n_c = get_f64(&c.input, "N_c");
    let cs = get_i64(&c.input, "cycle_seconds");
    let actual = open_cycle(now, h_c, n_c, cs);

    let expected_state = c.expected.get("state").unwrap_or_else(|| {
        panic!("case '{}' missing 'state' field in expected", c.id);
    });
    assert_eq!(
        actual.cycle_index,
        get_i64(expected_state, "cycle_index"),
        "case '{}' open_cycle cycle_index mismatch",
        c.id
    );
    assert_eq!(
        actual.h_c,
        get_i8(expected_state, "h_c"),
        "case '{}' open_cycle h_c mismatch",
        c.id
    );
    assert_close(
        actual.n_c,
        get_f64(expected_state, "N_c"),
        &c.id,
        "open_cycle.N_c",
    );
    assert_close(
        actual.opened_at,
        get_f64(expected_state, "opened_at"),
        &c.id,
        "open_cycle.opened_at",
    );
    assert_eq!(
        actual.cycle_seconds,
        get_i64(expected_state, "cycle_seconds"),
        "case '{}' open_cycle cycle_seconds mismatch",
        c.id
    );
}

fn check_enforce(c: &ParityCase) {
    let mut state = parse_optional_state(&c.input["state"]);
    let now = get_f64(&c.input, "now");
    let proposed_h = get_i8(&c.input, "proposed_h");
    let proposed_n = get_f64(&c.input, "proposed_N");
    let emergency_override = get_bool(&c.input, "emergency_override");
    // The Python reference uses DEFAULT_CYCLE_SECONDS for enforce fixtures
    // unless the state carries a specific cadence. Mirror that: if there's
    // a state with a non-default cycle_seconds, pass it through; else 3600.
    let cycle_seconds = state.map(|s| s.cycle_seconds).unwrap_or(3600);

    let result = enforce(
        &mut state,
        now,
        proposed_h,
        proposed_n,
        emergency_override,
        cycle_seconds,
    );

    let expected_h = get_i8(&c.expected, "h_eff");
    let expected_n = get_f64(&c.expected, "n_eff");
    assert_eq!(
        result.h_eff, expected_h,
        "case '{}' enforce h_eff mismatch: got {}, expected {}",
        c.id, result.h_eff, expected_h
    );
    assert_close(result.n_eff, expected_n, &c.id, "enforce.n_eff");
}

fn check_would_violate_lock(c: &ParityCase) {
    let state = parse_optional_state(&c.input["state"]);
    let now = get_f64(&c.input, "now");
    let proposed_h = get_i8(&c.input, "proposed_h");
    let actual = would_violate_lock(state.as_ref(), now, proposed_h);
    let expected = get_bool(&c.expected, "value");
    assert_eq!(
        actual, expected,
        "case '{}' would_violate_lock mismatch: got {}, expected {}",
        c.id, actual, expected
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// Top-level test
// ─────────────────────────────────────────────────────────────────────────────

#[test]
fn python_parity_funding_cycle_lock() {
    let doc = match load_fixture_doc() {
        Some(d) => d,
        None => {
            eprintln!(
                "parity: funding_cycle_lock fixture not present at expected path; skipping"
            );
            return;
        }
    };
    assert!(
        !doc.cases.is_empty(),
        "funding_cycle_lock fixture has zero cases"
    );

    let mut by_fn: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    for case in &doc.cases {
        match case.function.as_str() {
            "cycle_index" => check_cycle_index(case),
            "cycle_phase" => check_cycle_phase(case),
            "seconds_to_cycle_end" => check_seconds_to_cycle_end(case),
            "is_locked" => check_is_locked(case),
            "open_cycle" => check_open_cycle(case),
            "enforce" => check_enforce(case),
            "would_violate_lock" => check_would_violate_lock(case),
            other => panic!(
                "case '{}': unknown function '{}' in parity fixture",
                case.id, other
            ),
        }
        *by_fn.entry(case.function.clone()).or_insert(0) += 1;
    }

    // Sanity: every function the fixture covers must have been exercised.
    let expected_fns = [
        "cycle_index",
        "cycle_phase",
        "seconds_to_cycle_end",
        "is_locked",
        "open_cycle",
        "enforce",
        "would_violate_lock",
    ];
    for fn_name in expected_fns {
        assert!(
            by_fn.contains_key(fn_name),
            "parity fixture missing coverage for function '{}'",
            fn_name
        );
    }

    // Dump a compact summary to stderr for CI visibility.
    let total: usize = by_fn.values().sum();
    eprintln!(
        "parity: funding_cycle_lock {} cases across {} functions",
        total,
        by_fn.len()
    );
    for (fn_name, count) in &by_fn {
        eprintln!("  {:<25} {} cases", fn_name, count);
    }
}
