//! Byte-exact parity: Rust `prepare_message` ↔ Python `prepare_message`
//! from `pacifica-fi/python-sdk` (`common/utils.py`).
//!
//! The fixture `tests/fixtures/pacifica_signing.json` is generated by a
//! Python script that implements the SDK algorithm (`sort_json_keys` +
//! `json.dumps(separators=(",", ":"))`). If our Rust implementation
//! deviates by a single byte — key order, number formatting, whitespace,
//! escape sequences — this test fails.
//!
//! This is the strongest possible unit-level guarantee short of running
//! the official Python SDK as a subprocess; we chose fixtures so the
//! test is hermetic (no Python required at CI time).

use bot_adapters::pacifica_sign::prepare_message;
use serde::Deserialize;
use serde_json::Value;

#[derive(Debug, Deserialize)]
struct FixtureCase {
    name: String,
    header: Value,
    payload: Value,
    expected_message: String,
}

fn load_fixtures() -> Vec<FixtureCase> {
    let raw = std::fs::read_to_string("tests/fixtures/pacifica_signing.json")
        .expect("read tests/fixtures/pacifica_signing.json");
    serde_json::from_str(&raw).expect("parse pacifica_signing.json")
}

#[test]
fn rust_prepare_message_matches_python_sdk_byte_for_byte() {
    let cases = load_fixtures();
    assert!(!cases.is_empty(), "fixture file must contain cases");

    let mut failures = Vec::new();
    for case in cases {
        let got = prepare_message(&case.header, &case.payload).expect("prepare_message");
        if got != case.expected_message {
            failures.push(format!(
                "case `{}`:\n  expected (python): {}\n  got (rust)       : {}",
                case.name, case.expected_message, got
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "Python↔Rust signing divergence:\n{}",
        failures.join("\n\n")
    );
}
